name: Deploy Bot

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9'
      - name: Install caprover
        run: sudo npm install -g caprover

      - name: Install dependencies
        run: yarn install --non-interactive

      - name: Compile assets
        run: yarn build

      - name: Create tar
        run: tar -cvf ./deploy.tar --exclude='*.map' ecosystem.config.js captain-definition package.json yarn.lock Dockerfile dist/*

      - name: Deploy
        run: caprover deploy -h ${{ secrets.CAPROVER_SERVER_PROD }} -p ${{ secrets.CAPROVER_PASSWORD_PROD }} -a chikha -t ./deploy.tar
